server:
  port: ${PORT:10378}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nhnacademy-be10-sajotuna/config-repo
          default-label: dev
          username: flashdragon
          password: ${{ secrets.CONFIG_TOKEN }}
  application:
    name: config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10372/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,shutdown

logging:
  level:
    org.springframework.cloud.gateway: DEBUG